/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://repo.papermc.io/repository/maven-public/")
    }
}

rootProject.name = "Spoofer"
include(":Spoofer-API")
include(":Spoofer-Core")
include(":Spoofer-1.19.2")
include(":Spoofer-1.19.3")
include(":Spoofer-1.19.4")
// include(":1.18.2")
include("Spoofer-Demo")
include("Spoofer-1.20.2")
