/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.thatsmusic99.java-conventions")
}

dependencies {
    implementation(project(":Spoofer-API"))
}

description = "Spoofer-Core"
