/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.thatsmusic99.java-conventions")
    id("io.papermc.paperweight.userdev") version "1.3.8"
}

dependencies {
    implementation(project(":Spoofer-Core"))
    paperDevBundle("1.18.2-R0.1-SNAPSHOT")
}

description = "1.18.2"
