/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.thatsmusic99.java-conventions")
    id("io.papermc.paperweight.userdev") version "1.3.8"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

dependencies {
    implementation(project(":Spoofer-Core"))
    paperDevBundle("1.19.2-R0.1-SNAPSHOT")
}

task("tryPlugin") {
    dependsOn("shadowJar")

    doFirst {
        copy {
            from(buildDir.resolve("libs/1.19.2-1.0-SNAPSHOT-dev-all.jar"))
            into(buildDir.resolve("C:/Users/holly/Documents/Server_NMS/plugins"))
        }
    }
}

description = "1.19.2"
